image: docker:latest
services:
  - docker:dind

stages:
  - build
  - test
  - docker-build-push
  - deploy

currency-getter-build:
  image: gradle:7.2.0-jdk11
  stage: build
  script: "gradle build"
  artifacts:
    paths:
      - build/libs/*.jar

currency-getter-test:
  image: gradle:7.2.0-jdk11
  stage: test
  script: "gradle test"

currency-getter-build-push:
  stage: docker-build-push
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t socks .
    - docker tag socks:latest registry.gitlab.com/romanovolegd/socks/socks:$CI_COMMIT_SHORT_SHA
    - docker push registry.gitlab.com/romanovolegd/socks/socks:$CI_COMMIT_SHORT_SHA
    - echo "Built and pushed socks:$CI_COMMIT_SHORT_SHA successfully"

currency-getter-deploy:
  image: google/cloud-sdk
  stage: deploy
  when: manual
  script:
    - echo "$GOOGLE_KEY" > key.json
    - gcloud auth activate-service-account --key-file key.json
    - gcloud config list
    - gcloud config set compute/zone europe-north1-a
    - gcloud config set compute/region europe-north1
    - gcloud config set project capable-door-325120
    - gcloud config set disable_usage_reporting True
    - gcloud config list
    - gcloud compute instances update-container $VM_INSTANCE --container-image registry.gitlab.com/romanovolegd/socks/socks:$CI_COMMIT_SHORT_SHA --container-restart-policy on-failure
      --container-env DB_HOST=34.125.229.163,POSTGRES_DB=postgres,DB_USERNAME=postgres,POSTGRES_PASSWORD=password \
